# database generated on 2022-11-15 16:53 GMT
!!omap
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - add
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/addi-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - addi
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/and-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - and
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/andi-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - andi
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/auipc-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - auipc
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/beq-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - beq
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bge-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bge
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bgeu-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bgeu
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/blt-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - blt
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bltu-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bltu
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bne-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bne
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/fence-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fence
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jal-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - jal
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jalr-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - jalr
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lb-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lb-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lbu-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lbu-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lh-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lh-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lhu-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lhu-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lui-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lui
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lw-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lw-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/misalign1-jalr-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign1-jalr
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/or-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - or
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/ori-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - ori
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sb-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sb-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sh-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sh-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sll-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sll
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slli-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slli
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slt-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slt
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slti-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slti
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltiu-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sltiu
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltu-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sltu
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sra-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sra
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srai-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srai
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srl-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srl
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srli-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srli
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sub-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sub
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sw-align-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sw-align
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xor-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - xor
- ? /home/moon/RISCV-Hackathon/demo/RISCV-32I-Single-Cycle-Processor/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xori-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - xori
